export const MOVE_PLAYER = "MOVE_PLAYER";
export const GET_PLAYER = "GET_PLAYER";
export const ADD_TILES = "ADD_TILES";
export const SET_NEWGAME = "SET_NEWGAME";
export const GET_PLAYER_SUCCESS = "GET_PLAYER_SUCCESS";
export const GET_PLAYER_FAILURE = "GET_PLAYER_FAILURE";
